name: 'Release: Publish to NuGet'

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  createArtifacts:
    name: Generate NuGet Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
    
      - name: Set Environment Variables
        uses: ./.github/actions/set-env

      - uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build Solution
        run: dotnet build -c Release --no-restore

      - name: 'Pack and Publish: Core'
        uses: ./.github/actions/pack-and-publish
        with:
          projectPath: './src/XperienceCommunity.DevTools.PageBuilderTagHelpers'
          preReleaseVersion: ${{ github.run_number }}-${{ github.run_attempt }}
          projectSubfolder: 'taghelper'
      - name: 'Pack and Publish: Data'
        uses: ./.github/actions/pack-and-publish
        with:
          projectPath: './src/XperienceCommunity.DevTools.PageBuilderUtilities'
          preReleaseVersion: ${{ github.run_number }}-${{ github.run_attempt }}
          projectSubfolder: 'utilities'

  publishPreReleaseTagHelper:
    name: Publish PreRelease NuGet Package (taghelper)
    environment: prerelease
    needs: createArtifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: prerelease-taghelper
          
      - name: Publish NuGet Package
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
  publishPreReleaseUtilities:
    name: Publish PreRelease NuGet Package (utilities)
    environment: prerelease
    needs: createArtifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: prerelease-utilities
          
      - name: Publish NuGet Package
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
  publishReleaseTagHelper:
    name: Publish Release NuGet Package
    environment: release
    needs: [createArtifacts, publishPreReleaseTagHelper]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: release-taghelper
          
      - name: Publish NuGet Package
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
  publishReleaseUtilities:
    name: Publish Release NuGet Package
    environment: release
    needs: [createArtifacts, publishPreReleaseUtilities]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: release-utilities
          
      - name: Publish NuGet Package
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}